#!/bin/sh
#
# Set up environment variables for general build tool to operate
#
export ZOPEN_TYPE="TARBALL"

ZOPEN_TARBALL_DIR=tar-1.34
export ZOPEN_TARBALL_URL="https://ftp.gnu.org/gnu/tar/${ZOPEN_TARBALL_DIR}.tar.gz"
export ZOPEN_TARBALL_DEPS="curl gzip make m4"

ZOPEN_GIT_DIR=git
export ZOPEN_GIT_URL="git://git.savannah.gnu.org/${ZOPEN_GIT_DIR}.git"
export ZOPEN_GIT_DEPS="git make m4 perl makeinfo autoconf automake"

export ZOPEN_EXTRA_LDFLAGS=""
export ZOPEN_CHECK=skip # test #11 hangs   

zopen_check_results()
{
  return 3 # non-functional
}

